/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreatePropertyParams {
  'title' : string,
  'furnishingStatus' : FurnishingStatus,
  'propertyType' : PropertyType,
  'permitNumber' : string,
  'description' : string,
  'price' : bigint,
  'areaSquareFeet' : bigint,
  'location' : string,
  'numberOfWashrooms' : bigint,
  'images' : Array<ExternalBlob>,
}
export type ExternalBlob = Uint8Array;
export type FurnishingStatus = { 'semiFurnished' : null } |
  { 'furnished' : null } |
  { 'unfurnished' : null };
export interface Property {
  'id' : bigint,
  'title' : string,
  'furnishingStatus' : FurnishingStatus,
  'propertyType' : PropertyType,
  'permitNumber' : string,
  'description' : string,
  'price' : bigint,
  'areaSquareFeet' : bigint,
  'location' : string,
  'numberOfWashrooms' : bigint,
  'images' : Array<ExternalBlob>,
}
export type PropertyType = { 'retail' : null } |
  { 'office' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProperty' : ActorMethod<[CreatePropertyParams], undefined>,
  'deleteProperty' : ActorMethod<[bigint], undefined>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getAutocompleteSuggestions' : ActorMethod<
    [string, [] | [bigint]],
    Array<string>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPropertiesByAreaRange' : ActorMethod<[bigint, bigint], Array<Property>>,
  'getPropertiesByFurnishingStatus' : ActorMethod<
    [FurnishingStatus],
    Array<Property>
  >,
  'getPropertiesByLocation' : ActorMethod<[string], Array<Property>>,
  'getPropertiesByPriceRange' : ActorMethod<[bigint, bigint], Array<Property>>,
  'getPropertiesByType' : ActorMethod<[PropertyType], Array<Property>>,
  'getPropertiesWithFullFilters' : ActorMethod<
    [string, PropertyType, FurnishingStatus, bigint, bigint, bigint, bigint],
    Array<Property>
  >,
  'getPropertyById' : ActorMethod<[bigint], Property>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProperty' : ActorMethod<[bigint, CreatePropertyParams], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];