/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FurnishingStatus = IDL.Variant({
  'semiFurnished' : IDL.Null,
  'furnished' : IDL.Null,
  'unfurnished' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'retail' : IDL.Null,
  'office' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreatePropertyParams = IDL.Record({
  'title' : IDL.Text,
  'furnishingStatus' : FurnishingStatus,
  'propertyType' : PropertyType,
  'permitNumber' : IDL.Text,
  'description' : IDL.Text,
  'areaName' : IDL.Text,
  'price' : IDL.Nat,
  'areaSquareFeet' : IDL.Nat,
  'location' : IDL.Text,
  'numberOfWashrooms' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'furnishingStatus' : FurnishingStatus,
  'propertyType' : PropertyType,
  'permitNumber' : IDL.Text,
  'description' : IDL.Text,
  'areaName' : IDL.Text,
  'price' : IDL.Nat,
  'areaSquareFeet' : IDL.Nat,
  'location' : IDL.Text,
  'numberOfWashrooms' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LocationSuggestion = IDL.Record({
  'area' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPropertyWithCode' : IDL.Func([CreatePropertyParams, IDL.Text], [], []),
  'deletePropertyWithCode' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLocationSuggestions' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Vec(LocationSuggestion)],
      ['query'],
    ),
  'getPropertiesByArea' : IDL.Func([IDL.Text], [IDL.Vec(Property)], ['query']),
  'getPropertiesByAreaRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getPropertiesByFurnishingStatus' : IDL.Func(
      [FurnishingStatus],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getPropertiesByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getPropertiesByPriceRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getPropertiesByType' : IDL.Func(
      [PropertyType],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getPropertiesWithFullFilters' : IDL.Func(
      [
        IDL.Text,
        PropertyType,
        FurnishingStatus,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getPropertyById' : IDL.Func([IDL.Nat], [Property], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPropertiesByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'updatePropertyWithCode' : IDL.Func(
      [IDL.Nat, CreatePropertyParams, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FurnishingStatus = IDL.Variant({
    'semiFurnished' : IDL.Null,
    'furnished' : IDL.Null,
    'unfurnished' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'retail' : IDL.Null,
    'office' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreatePropertyParams = IDL.Record({
    'title' : IDL.Text,
    'furnishingStatus' : FurnishingStatus,
    'propertyType' : PropertyType,
    'permitNumber' : IDL.Text,
    'description' : IDL.Text,
    'areaName' : IDL.Text,
    'price' : IDL.Nat,
    'areaSquareFeet' : IDL.Nat,
    'location' : IDL.Text,
    'numberOfWashrooms' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'furnishingStatus' : FurnishingStatus,
    'propertyType' : PropertyType,
    'permitNumber' : IDL.Text,
    'description' : IDL.Text,
    'areaName' : IDL.Text,
    'price' : IDL.Nat,
    'areaSquareFeet' : IDL.Nat,
    'location' : IDL.Text,
    'numberOfWashrooms' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LocationSuggestion = IDL.Record({
    'area' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPropertyWithCode' : IDL.Func(
        [CreatePropertyParams, IDL.Text],
        [],
        [],
      ),
    'deletePropertyWithCode' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLocationSuggestions' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Vec(LocationSuggestion)],
        ['query'],
      ),
    'getPropertiesByArea' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertiesByAreaRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertiesByFurnishingStatus' : IDL.Func(
        [FurnishingStatus],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertiesByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertiesByPriceRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertiesByType' : IDL.Func(
        [PropertyType],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertiesWithFullFilters' : IDL.Func(
        [
          IDL.Text,
          PropertyType,
          FurnishingStatus,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertyById' : IDL.Func([IDL.Nat], [Property], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPropertiesByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'updatePropertyWithCode' : IDL.Func(
        [IDL.Nat, CreatePropertyParams, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };